# Generated by Django 5.2.8 on 2025-12-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = []
